name: CI/CD Frontend

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: nicolasanachuri
          password: dckr_pat_t47vl56ElQj0i4a-OEelOQlZOVI

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: nicolasanachuri/frontend:latest
